"""On-the-fly pool chemistry advice, generated by Claude.

Given a pool's full specification and its recent reading history, this asks
Claude (Opus 4.8) to reason about the water balance holistically and return a
prioritised, structured set of recommendations — including concrete dosing
estimates tailored to the pool's actual volume and sanitiser type.

If no ``ANTHROPIC_API_KEY`` is configured (or the API call fails), it falls
back to a simple deterministic range check so the app still works out of the
box in a fresh container.
"""
from __future__ import annotations

import logging
from typing import Optional

from pydantic import BaseModel, Field

from . import chemistry
from .chemistry import Assessment, Recommendation, Severity
from .config import get_settings
from .models import Pool, Reading

logger = logging.getLogger("pool_tracking.advice")

# Stable, cacheable expert prompt. Keep this byte-for-byte constant so prompt
# caching keys on it across requests (no timestamps / per-request values here).
SYSTEM_PROMPT = """\
You are a meticulous residential swimming-pool water chemistry advisor. You are \
given a pool's specification and its most recent water test readings, and you \
produce clear, safe, prioritised guidance for a non-expert pool owner.

Principles:
- Reason holistically: parameters interact. Balance Total Alkalinity before \
fine-tuning pH; interpret Free Chlorine against Cyanuric Acid (stabiliser); \
treat ORP as a sanitiser-strength cross-check; account for the sanitiser type \
(chlorine, saltwater chlorinator, or bromine), surface material, and whether \
the pool is indoor or outdoor.
- When a parameter needs adjustment, give a concrete dosing estimate computed \
for THIS pool's volume and a named product (e.g. calcium hypochlorite, liquid \
chlorine, sodium bicarbonate, soda ash, muriatic acid, cyanuric acid, calcium \
chloride, pool salt). Estimate conservatively, tell the owner to add gradually \
with the pump running, and to re-test before adding more.
- Severity levels: "ok" (in range), "low" (minor/informational), "warning" \
(out of range, act soon), "critical" (unsafe to swim or risk of damage, act now). \
Free chlorine below ~0.5 ppm is critical (water is effectively unsanitised).
- Always include the safety basics: never mix pool chemicals together, add \
chemicals to water (not water to chemicals), and keep swimmers out until levels \
are safe.
- Produce one recommendation per relevant parameter, ordered most urgent first, \
plus a one- or two-sentence overall summary. Be concise and practical. Do not \
invent readings that were not provided; if a key parameter is missing, you may \
note that it should be tested.
- Also produce a short, ordered "next steps" to-do list: the concrete actions \
the owner should take to bring the water into balance, in the order they should \
do them (adjust alkalinity before pH, etc.). Each step is one clear action with \
the product and dose where relevant, what to do (pump running, add to water, add \
gradually), and when to re-test. If the water is already balanced, give at most \
one light maintenance step or leave it empty.
- Use ALL the readings provided. The input includes the latest reading, every \
reading taken so far today, and recent daily history. Compare today's readings \
to spot intra-day movement (e.g. chlorine falling through a hot afternoon) and \
compare against recent days for slower trends. Base the dosing on the latest \
reading but explain any trend you see.
- Be consistent and deterministic. Given the same inputs you must give the same \
recommendations and the same dosing numbers every time. Use the standard target \
ranges below and standard dosing relationships (e.g. ~1.5 g of calcium \
hypochlorite per 1000 L raises Free Chlorine by ~1 ppm; ~17 g of sodium \
bicarbonate per 1000 L raises Total Alkalinity by ~10 ppm), scaled to this \
pool's volume and rounded sensibly. Do not re-derive figures differently on \
repeat runs or introduce new caveats that change the numbers.

Reference target ranges for a typical residential pool (use judgement to adapt \
to the specific pool): pH 7.2-7.6; Total Alkalinity 80-120 ppm; Free Chlorine \
1-3 ppm (or ~7.5% of Cyanuric Acid when stabiliser is present); Cyanuric Acid \
30-50 ppm outdoor (60-80 for salt pools, near 0 indoor); Calcium Hardness \
200-400 ppm; Salt 2700-3400 ppm (saltwater pools); ORP 650-750 mV.

When weather data is provided for the reading dates, use it to explain changes \
in the readings: hot, sunny, high-UV days accelerate chlorine loss and \
evaporation (raising salt/hardness concentration); heavy rain dilutes the water \
and can drop pH and sanitiser; high bather load on warm days raises demand. \
Call out any plausible weather-driven trend you can see across the history."""


class AdviceRecommendation(BaseModel):
    parameter: str = Field(description="The water parameter, e.g. 'pH' or 'Free chlorine'.")
    severity: str = Field(description="One of: ok, low, warning, critical.")
    message: str = Field(description="Plain-language explanation of the reading and why it matters.")
    action: Optional[str] = Field(
        default=None,
        description="Concrete corrective action with a dosing estimate, or null if none needed.",
    )


class AdviceResult(BaseModel):
    summary: str = Field(description="A one or two sentence overall assessment of the water.")
    recommendations: list[AdviceRecommendation]
    next_steps: list[str] = Field(
        default_factory=list,
        description=(
            "An ordered, practical to-do list to rebalance THIS pool, most urgent "
            "first. Each step is a single concrete action with the product and "
            "dose where relevant, plus when to re-test. Empty if the water is "
            "already balanced."
        ),
    )


def _short_error(exc: Exception) -> str:
    """A short, single-line description of an exception for the UI.

    Anthropic SDK errors often carry the API's own message (e.g. a deprecated
    parameter), which is the most useful thing to show. Trimmed and flattened so
    it stays on one line and can't dump a huge JSON body into the page.
    """
    text = " ".join(str(exc).split())
    if len(text) > 160:
        text = text[:157] + "…"
    return text or exc.__class__.__name__


def _severity(value: str) -> Severity:
    try:
        return Severity(value.strip().lower())
    except ValueError:
        return Severity.warning


def _reading_to_dict(r: Reading, weather: dict | None = None) -> dict:
    fields = {
        "ph": "pH",
        "free_chlorine": "free_chlorine_ppm",
        "total_chlorine": "total_chlorine_ppm",
        "total_alkalinity": "total_alkalinity_ppm",
        "cyanuric_acid": "cyanuric_acid_ppm",
        "calcium_hardness": "calcium_hardness_ppm",
        "salt": "salt_ppm",
        "orp": "orp_mv",
        "ec": "ec_us_cm",
        "tds": "tds_ppm",
        "temperature_c": "temperature_c",
    }
    out: dict = {"taken_at": r.taken_at.isoformat(), "source": r.source.value}
    for attr, key in fields.items():
        val = getattr(r, attr)
        if val is not None:
            out[key] = val
    if weather:
        summary = weather.get(r.taken_at.date().isoformat())
        if summary is not None:
            out["weather"] = {
                "description": summary.description,
                "temp_max_c": summary.temp_max_c,
                "temp_min_c": summary.temp_min_c,
                "precipitation_mm": summary.precipitation_mm,
                "uv_index_max": summary.uv_index_max,
                "wind_max_kmh": summary.wind_max_kmh,
            }
    return out


def _local_today(pool: Pool):
    """The current date in the pool's local timezone (UTC fallback)."""
    from datetime import datetime, timezone
    from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

    now = datetime.now(timezone.utc)
    if pool.timezone:
        try:
            return now.astimezone(ZoneInfo(pool.timezone)).date()
        except (ZoneInfoNotFoundError, ValueError):
            pass
    return now.date()


def _is_on_local_date(reading: Reading, target_date, pool: Pool) -> bool:
    from datetime import timezone
    from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

    taken = reading.taken_at
    if taken.tzinfo is None:
        taken = taken.replace(tzinfo=timezone.utc)
    if pool.timezone:
        try:
            return taken.astimezone(ZoneInfo(pool.timezone)).date() == target_date
        except (ZoneInfoNotFoundError, ValueError):
            pass
    return taken.astimezone(timezone.utc).date() == target_date


def _build_pool_payload(
    pool: Pool, readings: list[Reading], weather: dict | None, notes: str | None
) -> str:
    import json

    from .models import estimate_volume_litres

    today = _local_today(pool)
    todays_readings = [r for r in readings if _is_on_local_date(r, today, pool)]

    payload = {
        "pool": {
            "name": pool.name,
            "volume_litres": pool.volume_litres,
            "volume_us_gallons": round(pool.volume_litres / 3.78541, 0),
            "volume_estimate_from_dimensions_litres": estimate_volume_litres(
                pool.shape, pool.length_m, pool.width_m, pool.avg_depth_m
            ),
            "type": pool.pool_type.value if pool.pool_type else None,
            "shape": pool.shape.value if pool.shape else None,
            "dimensions_m": {
                "length": pool.length_m,
                "width": pool.width_m,
                "avg_depth": pool.avg_depth_m,
            },
            "sanitiser": pool.sanitizer.value,
            "surface": pool.surface.value,
            "setting": "indoor" if pool.indoor else "outdoor",
            "location": pool.location_name,
        },
        "owner_notes": notes or None,
        "local_date": today.isoformat(),
        "latest_reading": _reading_to_dict(readings[0], weather) if readings else None,
        "readings_today": [_reading_to_dict(r, weather) for r in todays_readings],
        "recent_history": [_reading_to_dict(r, weather) for r in readings[1:15]],
    }
    return json.dumps(payload, indent=2)


def generate_advice(
    pool: Pool,
    readings: list[Reading],
    weather: dict | None = None,
    notes: str | None = None,
) -> Assessment:
    """Return an :class:`Assessment` for the pool's latest reading.

    ``readings`` should be ordered newest-first; ``readings[0]`` is assessed,
    earlier ones are supplied as trend context. ``weather`` optionally maps ISO
    dates to :class:`~app.weather.WeatherSummary` so Claude can correlate the
    readings with the weather on those days. ``notes`` is free-text context the
    owner has supplied about the pool (e.g. recent treatments, surroundings).
    """
    settings = get_settings()
    if not readings:
        return Assessment(summary="No readings yet — add a water test to get advice.")

    if not settings.anthropic_api_key:
        return chemistry.fallback_assessment(pool, readings[0])

    try:
        return _generate_with_claude(pool, readings, weather, notes, settings)
    except Exception as exc:  # noqa: BLE001 - never let advice failure break the page
        logger.exception("Claude advice generation failed; using fallback")
        return chemistry.fallback_assessment(
            pool,
            readings[0],
            reason=(
                "AI advice could not be generated just now (the Claude request "
                f"failed: {_short_error(exc)}). Press Refresh to try again."
            ),
        )


def _generate_with_claude(
    pool: Pool, readings: list[Reading], weather: dict | None, notes: str | None, settings
) -> Assessment:
    import anthropic

    client = anthropic.Anthropic(api_key=settings.anthropic_api_key)
    user_content = (
        "Assess this pool's water and give dosing advice for the latest reading. "
        "Where weather is included, note any links between the weather and the "
        "readings. Take the owner's notes into account where relevant.\n\n"
        + _build_pool_payload(pool, readings, weather, notes)
    )

    # This model deprecates `temperature`, so we can't force greedy decoding.
    # Repeatability instead comes from the system prompt (fixed target ranges and
    # standard dosing formulas) and from not using adaptive extended thinking,
    # whose variable reasoning made advice drift between runs. Reasoning depth is
    # governed by `effort`.
    response = client.messages.parse(
        model=settings.advice_model,
        max_tokens=4000,
        output_config={"effort": settings.advice_effort},
        system=[
            {
                "type": "text",
                "text": SYSTEM_PROMPT,
                "cache_control": {"type": "ephemeral"},
            }
        ],
        messages=[{"role": "user", "content": user_content}],
        output_format=AdviceResult,
    )

    result = response.parsed_output
    assessment = Assessment(
        summary=result.summary, source="claude", next_steps=list(result.next_steps)
    )
    for rec in result.recommendations:
        assessment.recommendations.append(
            Recommendation(
                parameter=rec.parameter,
                severity=_severity(rec.severity),
                message=rec.message,
                action=rec.action,
            )
        )
    return assessment


def regenerate_pool_advice(db, pool: Pool) -> bool:
    """Generate fresh advice for ``pool`` and upsert its stored ``PoolAdvice`` row.

    Shared by the manual triggers (new reading / Refresh) and the twice-daily
    scheduler. Returns ``True`` if advice was written, ``False`` if the pool has
    no readings to assess. Commits its own transaction.
    """
    from datetime import datetime, timezone

    from sqlalchemy import select

    from . import weather as weather_mod
    from .models import PoolAdvice, Reading

    readings = db.scalars(
        select(Reading).where(Reading.pool_id == pool.id).order_by(Reading.taken_at.desc())
    ).all()
    if not readings:
        return False

    try:
        weather_by_date = weather_mod.weather_for_dates(
            db, pool, {r.taken_at.date() for r in readings}
        )
    except Exception:  # noqa: BLE001 - weather is a nice-to-have, never fatal
        weather_by_date = {}

    assessment = generate_advice(pool, list(readings), weather_by_date, notes=pool.notes)
    payload = serialise_assessment(assessment)

    advice = db.scalar(select(PoolAdvice).where(PoolAdvice.pool_id == pool.id))
    if advice is None:
        db.add(PoolAdvice(pool_id=pool.id, reading_id=readings[0].id, payload=payload))
    else:
        advice.payload = payload
        advice.reading_id = readings[0].id
        advice.generated_at = datetime.now(timezone.utc)
    db.commit()
    return True


def serialise_assessment(assessment: Assessment) -> str:
    """Serialise an :class:`Assessment` to a JSON string for persistence."""
    import json

    return json.dumps(
        {
            "summary": assessment.summary,
            "source": assessment.source,
            "next_steps": list(assessment.next_steps),
            "recommendations": [
                {
                    "parameter": r.parameter,
                    "severity": r.severity.value,
                    "message": r.message,
                    "action": r.action,
                }
                for r in assessment.recommendations
            ],
        }
    )


def deserialise_assessment(payload: str) -> Assessment:
    """Rebuild an :class:`Assessment` from a :func:`serialise_assessment` blob."""
    import json

    data = json.loads(payload)
    assessment = Assessment(
        summary=data.get("summary", ""),
        source=data.get("source", "fallback"),
        next_steps=list(data.get("next_steps", [])),
    )
    for rec in data.get("recommendations", []):
        assessment.recommendations.append(
            Recommendation(
                parameter=rec.get("parameter", ""),
                severity=_severity(rec.get("severity", "warning")),
                message=rec.get("message", ""),
                action=rec.get("action"),
            )
        )
    return assessment
