"""On-the-fly pool chemistry advice, generated by Claude.

Given a pool's full specification and its recent reading history, this asks
Claude (Opus 4.8) to reason about the water balance holistically and return a
prioritised, structured set of recommendations — including concrete dosing
estimates tailored to the pool's actual volume and sanitiser type.

If no ``ANTHROPIC_API_KEY`` is configured (or the API call fails), it falls
back to a simple deterministic range check so the app still works out of the
box in a fresh container.
"""
from __future__ import annotations

import logging
from typing import Optional

from pydantic import BaseModel, Field

from . import chemistry
from .chemistry import Assessment, Recommendation, Severity
from .config import get_settings
from .models import Pool, Reading

logger = logging.getLogger("pool_tracking.advice")

# Stable, cacheable expert prompt. Keep this byte-for-byte constant so prompt
# caching keys on it across requests (no timestamps / per-request values here).
SYSTEM_PROMPT = """\
You are a meticulous residential swimming-pool water chemistry advisor. You are \
given a pool's specification and its most recent water test readings, and you \
produce clear, safe, prioritised guidance for a non-expert pool owner.

Principles:
- Reason holistically: parameters interact. Balance Total Alkalinity before \
fine-tuning pH; interpret Free Chlorine against Cyanuric Acid (stabiliser); \
treat ORP as a sanitiser-strength cross-check; account for the sanitiser type \
(chlorine, saltwater chlorinator, or bromine), surface material, and whether \
the pool is indoor or outdoor.
- When a parameter needs adjustment, give a concrete dosing estimate computed \
for THIS pool's volume and a named product (e.g. calcium hypochlorite, liquid \
chlorine, sodium bicarbonate, soda ash, muriatic acid, cyanuric acid, calcium \
chloride, pool salt). Estimate conservatively, tell the owner to add gradually \
with the pump running, and to re-test before adding more.
- Severity levels: "ok" (in range), "low" (minor/informational), "warning" \
(out of range, act soon), "critical" (unsafe to swim or risk of damage, act now). \
Free chlorine below ~0.5 ppm is critical (water is effectively unsanitised).
- Always include the safety basics: never mix pool chemicals together, add \
chemicals to water (not water to chemicals), and keep swimmers out until levels \
are safe.
- Produce one recommendation per relevant parameter, ordered most urgent first, \
plus a one- or two-sentence overall summary. Be concise and practical. Do not \
invent readings that were not provided; if a key parameter is missing, you may \
note that it should be tested.

Reference target ranges for a typical residential pool (use judgement to adapt \
to the specific pool): pH 7.2-7.6; Total Alkalinity 80-120 ppm; Free Chlorine \
1-3 ppm (or ~7.5% of Cyanuric Acid when stabiliser is present); Cyanuric Acid \
30-50 ppm outdoor (60-80 for salt pools, near 0 indoor); Calcium Hardness \
200-400 ppm; Salt 2700-3400 ppm (saltwater pools); ORP 650-750 mV.

When weather data is provided for the reading dates, use it to explain changes \
in the readings: hot, sunny, high-UV days accelerate chlorine loss and \
evaporation (raising salt/hardness concentration); heavy rain dilutes the water \
and can drop pH and sanitiser; high bather load on warm days raises demand. \
Call out any plausible weather-driven trend you can see across the history."""


class AdviceRecommendation(BaseModel):
    parameter: str = Field(description="The water parameter, e.g. 'pH' or 'Free chlorine'.")
    severity: str = Field(description="One of: ok, low, warning, critical.")
    message: str = Field(description="Plain-language explanation of the reading and why it matters.")
    action: Optional[str] = Field(
        default=None,
        description="Concrete corrective action with a dosing estimate, or null if none needed.",
    )


class AdviceResult(BaseModel):
    summary: str = Field(description="A one or two sentence overall assessment of the water.")
    recommendations: list[AdviceRecommendation]


def _severity(value: str) -> Severity:
    try:
        return Severity(value.strip().lower())
    except ValueError:
        return Severity.warning


def _reading_to_dict(r: Reading, weather: dict | None = None) -> dict:
    fields = {
        "ph": "pH",
        "free_chlorine": "free_chlorine_ppm",
        "total_chlorine": "total_chlorine_ppm",
        "total_alkalinity": "total_alkalinity_ppm",
        "cyanuric_acid": "cyanuric_acid_ppm",
        "calcium_hardness": "calcium_hardness_ppm",
        "salt": "salt_ppm",
        "orp": "orp_mv",
        "tds": "tds_ppm",
        "temperature_c": "temperature_c",
    }
    out: dict = {"taken_at": r.taken_at.isoformat(), "source": r.source.value}
    for attr, key in fields.items():
        val = getattr(r, attr)
        if val is not None:
            out[key] = val
    if weather:
        summary = weather.get(r.taken_at.date().isoformat())
        if summary is not None:
            out["weather"] = {
                "description": summary.description,
                "temp_max_c": summary.temp_max_c,
                "temp_min_c": summary.temp_min_c,
                "precipitation_mm": summary.precipitation_mm,
                "uv_index_max": summary.uv_index_max,
                "wind_max_kmh": summary.wind_max_kmh,
            }
    return out


def _build_pool_payload(pool: Pool, readings: list[Reading], weather: dict | None) -> str:
    import json

    payload = {
        "pool": {
            "name": pool.name,
            "volume_litres": pool.volume_litres,
            "volume_us_gallons": round(pool.volume_litres / 3.78541, 0),
            "sanitiser": pool.sanitizer.value,
            "surface": pool.surface.value,
            "setting": "indoor" if pool.indoor else "outdoor",
            "location": pool.location_name,
        },
        "latest_reading": _reading_to_dict(readings[0], weather) if readings else None,
        "recent_history": [_reading_to_dict(r, weather) for r in readings[1:8]],
    }
    return json.dumps(payload, indent=2)


def generate_advice(
    pool: Pool, readings: list[Reading], weather: dict | None = None
) -> Assessment:
    """Return an :class:`Assessment` for the pool's latest reading.

    ``readings`` should be ordered newest-first; ``readings[0]`` is assessed,
    earlier ones are supplied as trend context. ``weather`` optionally maps ISO
    dates to :class:`~app.weather.WeatherSummary` so Claude can correlate the
    readings with the weather on those days.
    """
    settings = get_settings()
    if not readings:
        return Assessment(summary="No readings yet — add a water test to get advice.")

    if not settings.anthropic_api_key:
        return chemistry.fallback_assessment(pool, readings[0])

    try:
        return _generate_with_claude(pool, readings, weather, settings)
    except Exception:  # noqa: BLE001 - never let advice failure break the page
        logger.exception("Claude advice generation failed; using fallback")
        a = chemistry.fallback_assessment(pool, readings[0])
        a.summary = "AI advice was temporarily unavailable; showing a basic range check. " + a.summary
        return a


def _generate_with_claude(
    pool: Pool, readings: list[Reading], weather: dict | None, settings
) -> Assessment:
    import anthropic

    client = anthropic.Anthropic(api_key=settings.anthropic_api_key)
    user_content = (
        "Assess this pool's water and give dosing advice for the latest reading. "
        "Where weather is included, note any links between the weather and the "
        "readings.\n\n" + _build_pool_payload(pool, readings, weather)
    )

    response = client.messages.parse(
        model=settings.advice_model,
        max_tokens=4000,
        thinking={"type": "adaptive"},
        output_config={"effort": settings.advice_effort},
        system=[
            {
                "type": "text",
                "text": SYSTEM_PROMPT,
                "cache_control": {"type": "ephemeral"},
            }
        ],
        messages=[{"role": "user", "content": user_content}],
        output_format=AdviceResult,
    )

    result = response.parsed_output
    assessment = Assessment(summary=result.summary, source="claude")
    for rec in result.recommendations:
        assessment.recommendations.append(
            Recommendation(
                parameter=rec.parameter,
                severity=_severity(rec.severity),
                message=rec.message,
                action=rec.action,
            )
        )
    return assessment
